export enum ProductStatus {
	PAUSED = "PAUSED",
	ACTIVE = "ACTIVE",
	DELETE = "DELETE",
}

export enum ProductCollection {
	ELECTRONICS = "ELECTRONICS",
	APPAREL = "APPAREL",
	HOME_AND_LIVING = "HOME_AND_LIVING",
	BEAUTY_AND_PERSONAL_CARE = "BEAUTY_AND_PERSONAL_CARE",
	SPORTS_AND_OUTDOORS = "SPORTS_AND_OUTDOORS",
	TOYS_AND_GAMES = "TOYS_AND_GAMES",
	BOOKS_AND_MEDIA = "BOOKS_AND_MEDIA",
	GROCERY = "GROCERY",
	AUTOMOTIVE = "AUTOMOTIVE",
	HEALTH_AND_WELLNESS = "HEALTH_AND_WELLNESS",
	OTHERS = "OTHERS",
}
