export enum ProductStatus {
	PAUSED = "PAUSED",
	ACTIVE = "ACTIVE",
	DELETE = "DELETE",
	RECOMMEND = "RECOMMEND",
	DISCOUNT = "DISCOUNT",
	ADS = "ADS",
}
export enum ProductCollection {
	FRESH_PRODUCE = "FRESH_PRODUCE",
	DAIRY_PRODUCTS = "DAIRY_PRODUCTS",
	MEAT_AND_POULTRY = "MEAT_AND_POULTRY",
	BAKERY_ITEMS = "BAKERY_ITEMS",
	CANNED_FOODS = "CANNED_FOODS",
	BEVERAGES = "BEVERAGES",
}
